---
- name: Install tuned packages
  become: true
  community.general.pacman:
    name: "{{ base_tuned_packages }}"
    state: present

- name: Enable and start tuned
  become: true
  ansible.builtin.systemd_service:
    name: tuned.service
    enabled: true
    state: started

- name: Enable and start tuned-ppd
  become: true
  ansible.builtin.systemd_service:
    name: tuned-ppd.service
    enabled: true
    state: started
