---
# desktop
kde_state: absent
gnome_state: present
hyprland_state: absent

# network
networking_tailscale_state: absent

# virtualization
virtualization_libvirt_state: present

# filesystems
storage_zfs_state: absent
storage_zfs_zrepl_state: absent
backup_btrbk_state: present
