---
kde_state: present

storage_zfs_state: absent
storage_zfs_zrepl_state: absent
backup_btrbk_state: present
backup_resticprofile_state: present

backup_resticprofile_backup_sources:
  - "/home"
  - "/etc"
  - "/home/gorschu/data"
  - "/home/gorschu/data/general"
  - "/home/gorschu/data/media"
  - "/home/gorschu/data/projects"
