---
all:
  children:
    workstations:
      hosts:
        apollo:
          ansible_host: localhost
          ansible_connection: local
        hephaestus:
          ansible_host: localhost
          ansible_connection: local
        artemis:
          ansible_host: localhost
          ansible_connection: local
