---
desktop_gui_applications:
  - solaar
  - firefox
  - kitty
  - vicinae
  - qutebrowser

desktop_support_applications:
  - wl-clipboard

# Optional desktop apps (present/absent toggles)
desktop_ghostty_state: absent
desktop_vscode_state: present
desktop_beyondcompare_state: absent
