---
desktop_gui_applications:
  - solaar
  - firefox
  - kitty
  - vicinae
  - qutebrowser

desktop_support_applications:
  - wl-clipboard

# Optional desktop apps (present/absent toggles)
ghostty_state: absent
vscode_state: present
beyondcompare_state: absent
