---
# resticprofile role defaults

# resticprofile state: present or absent
backup_resticprofile_state: absent

# Backup sources - override in host_vars for machines with ZFS datasets etc.
backup_resticprofile_backup_sources:
  - "/home"
  - "/etc"
