---
# btrbk role defaults

backup_btrbk_state: present

backup_btrbk_jobs:
  - name: home
    description: home subvolume snapshot
    volume_mount: /mnt/btrfs_root
    subvolume: home
    log: /var/log/btrbk-home.log
    preserve_min: "2h"
    preserve: "48h 14d 4w 1m"
    schedule: hourly
  - name: root
    description: root subvolume snapshot
    volume_mount: /mnt/btrfs_root
    subvolume: root
    log: /var/log/btrbk-root.log
    preserve_min: "4h"
    preserve: "24h 7d"
    schedule: "*-*-* 00/4:00:00"
  - name: data
    description: data subvolume snapshot
    volume_mount: /mnt/btrfs_data
    subvolume: data
    log: /var/log/btrbk-data.log
    preserve_min: "2h"
    preserve: "48h 30d 2w 1m"
    schedule: hourly
